export const destinations = [
  {
    id: "mars",
    name: "Mars",
    section: "Work experience",
    eyebrow: "THE JOURNEY SO FAR",
    description: "Every role leaves a mark.",
    color: "#dc8060",
    radius: 2.25,
    orbitRadius: 13,
    speed: 0.024,
    phase: 3.65,
    inclination: 0.08,
    index: "01",
  },
  {
    id: "neptune",
    name: "Neptune",
    section: "Personal projects",
    eyebrow: "IDEAS IN THEIR OWN ORBIT",
    description: "Built with curiosity. Sent into the world.",
    color: "#7caee9",
    radius: 2.9,
    orbitRadius: 30,
    speed: 0.009,
    phase: 5.9,
    inclination: 0.07,
    index: "02",
  },
  {
    id: "saturn",
    name: "Saturn",
    section: "Certifications",
    eyebrow: "ALWAYS LEARNING",
    description: "A few milestones along the way.",
    color: "#d8bb83",
    radius: 2.65,
    orbitRadius: 24,
    speed: 0.012,
    phase: 0.72,
    inclination: 0.12,
    index: "03",
  },
  {
    id: "earth",
    name: "Earth",
    section: "About me",
    eyebrow: "A PLACE TO CALL HOME",
    description: "The person behind the pixels.",
    color: "#87bbae",
    radius: 1.85,
    orbitRadius: 8.5,
    speed: 0.034,
    phase: 2.05,
    inclination: 0.05,
    index: "04",
  },
  {
    id: "jupiter",
    name: "Jupiter",
    section: "Skills & tech stack",
    eyebrow: "TOOLS OF THE TRADE",
    description: "A growing world of things I love to build with.",
    color: "#bea1d5",
    radius: 3.4,
    orbitRadius: 18.5,
    speed: 0.017,
    phase: 4.95,
    inclination: 0.03,
    index: "05",
  },
  {
    id: "moon",
    name: "Moon",
    section: "Contact",
    eyebrow: "TRANSMISSION OPEN",
    description: "Great things begin with a hello.",
    color: "#c4ccd5",
    radius: 0.62,
    orbitRadius: 3.1,
    speed: 0.15,
    phase: 1,
    inclination: 0.1,
    index: "06",
  },
];
export const categoryColors = {
  cloud: "#ffaa45",
  security: "#b494f6",
  development: "#62b7ff",
  design: "#ee91bb",
};
